openapi: 3.1.0

servers:
  - url: http://localhost:3000
    description: Local Server

info:
  title: Backend for Kata Pokemon API
  version: 1.0.0

paths:
  /health:
    get:
      tags:
        - System
      summary: Health Check
      description: Endpoint to check if the API is up and running.
      operationId: healthCheck
      responses:
        '200':
          description: API is healthy and running properly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                    description: Status of the API health
                  data:
                    type: object
                    properties: {}

  /account:
    post:
      summary: Register New User
      description: |
        Register New User to Database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: User register succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                  message:
                    type: 'null'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [failed]
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        enum: [invalid-value]
                      message:
                        type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [failed]
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        enum: [internal-error]
                      message:
                        type: string
      x-codeSamples:
        - lang: curl
          source: |
            curl -X POST "http://localhost:4000/account" \
            -H "Content-Type: application/json" \
            --data '{"name": "Bambang"}'  

  /pokemon/information:
    post:
      summary: Get pokemon information
      description: |
        Get pokemon information by pokemon name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pokemonName:
                  type: string
      responses:
        '200':
          description: Success retrieve pokemon information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                  message:
                    type: 'null'
                  data:
                    type: object
                    properties:
                      information:
                        type: string
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [failed]
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        enum: [invalid-value]
                      message:
                        type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [failed]
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        enum: [internal-error]
                      message:
                        type: string
      x-codeSamples:
        - lang: curl
          source: |
            curl -X POST "http://localhost:4000/pokemon/information" \
            -H "Content-Type: application/json" \
            --data '{"pokemonName": "pikachu"}'
